stages:
 - build

Ubuntu:
 stage: build
 script:
  - date
  - hostname
  - uname -a
  - export CMAKE_EXTRA_ARGS="-DCLONE_SUBPROJECTS=ON"
  - export CMAKE_EXTRA_TARGETS="test"
  - export BUILD_GENERATOR="Unix Makefiles"
  - bash .gitlabci.sh
 tags:
  - ubuntu

OSX:
 stage: build
 script:
  - date
  - hostname
  - uname -a
  - export CMAKE_EXTRA_ARGS="-DCLONE_SUBPROJECTS=ON"
  - export CMAKE_EXTRA_TARGETS="test"
  - export BUILD_GENERATOR="Unix Makefiles"
  - bash .gitlabci.sh
 tags:
  - osx

Win7-vs14:
 stage: build
 script:
  - call %ENVFILESDIR%\Boost-1.64-vs14-x64.bat
  - set CMAKE_EXTRA_TARGETS=RUN_TESTS
  - set RUN_TESTS=1
  - set BUILD_GENERATOR=Visual Studio 14 Win64
  - set PATH=%PATH%;"c:\\Program Files (x86)\\Git\\bin"
  - set CMAKE_EXTRA_ARGS=-DCLONE_SUBPROJECTS=ON
  - bash.exe --login .gitlabci.sh
 tags:
  - win7
